name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flasktest-application-packages"
  EB_APPLICATION_NAME : "MyFlask"
  EB_ENVIRONMENT_NAME : "Myflask-env"
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME : "us-east=1"
  
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.8
        uses: actions/setup-python@v3
        with:
            python-version: "3.9.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
      - name: Lint with flake8 
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 app --count --select=E9,F63,F7,F82,W391 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytests
        run: pytest tests
      
      - name: Print about tests finish
        run: echo "Tests Finished"
  build:
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create .env
        run: |
          touch .env
          echo SECRET_KEY = ${{ secrets.SECRET_KEY }} >> .env
        
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
